//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurbineDataUtility.Model {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int SS1 {
            get {
                return ((int)(this["SS1"]));
            }
            set {
                this["SS1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-7")]
        public int CC2 {
            get {
                return ((int)(this["CC2"]));
            }
            set {
                this["CC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-7")]
        public int GO2 {
            get {
                return ((int)(this["GO2"]));
            }
            set {
                this["GO2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-8")]
        public int EH1 {
            get {
                return ((int)(this["EH1"]));
            }
            set {
                this["EH1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int FR1 {
            get {
                return ((int)(this["FR1"]));
            }
            set {
                this["FR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int RT1 {
            get {
                return ((int)(this["RT1"]));
            }
            set {
                this["RT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int SM1 {
            get {
                return ((int)(this["SM1"]));
            }
            set {
                this["SM1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"P:\\0_Projects\\US\\0_Operations\\_Monthly RAW pi data\\PiDownloadLog.csv\"")]
        public string LOG {
            get {
                return ((string)(this["LOG"]));
            }
            set {
                this["LOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int SM2 {
            get {
                return ((int)(this["SM2"]));
            }
            set {
                this["SM2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int TH1 {
            get {
                return ((int)(this["TH1"]));
            }
            set {
                this["TH1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int FO2 {
            get {
                return ((int)(this["FO2"]));
            }
            set {
                this["FO2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int FO1 {
            get {
                return ((int)(this["FO1"]));
            }
            set {
                this["FO1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int MH1 {
            get {
                return ((int)(this["MH1"]));
            }
            set {
                this["MH1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int FR2 {
            get {
                return ((int)(this["FR2"]));
            }
            set {
                this["FR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int FO3 {
            get {
                return ((int)(this["FO3"]));
            }
            set {
                this["FO3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver_Star_I")]
        public string SS1_LongName {
            get {
                return ((string)(this["SS1_LongName"]));
            }
            set {
                this["SS1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cedar_Creek_II")]
        public string CC2_LongName {
            get {
                return ((string)(this["CC2_LongName"]));
            }
            set {
                this["CC2_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goshen")]
        public string GO2_LongName {
            get {
                return ((string)(this["GO2_LongName"]));
            }
            set {
                this["GO2_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edom_Hill")]
        public string EH1_LongName {
            get {
                return ((string)(this["EH1_LongName"]));
            }
            set {
                this["EH1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flat_Ridge_I")]
        public string FR1_LongName {
            get {
                return ((string)(this["FR1_LongName"]));
            }
            set {
                this["FR1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Titan_I")]
        public string RT1_LongName {
            get {
                return ((string)(this["RT1_LongName"]));
            }
            set {
                this["RT1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sherbino_Mesa_1")]
        public string SM1_LongName {
            get {
                return ((string)(this["SM1_LongName"]));
            }
            set {
                this["SM1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sherbino_Mesa_II")]
        public string SM2_LongName {
            get {
                return ((string)(this["SM2_LongName"]));
            }
            set {
                this["SM2_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fowler_II")]
        public string FO2_LongName {
            get {
                return ((string)(this["FO2_LongName"]));
            }
            set {
                this["FO2_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fowler_I")]
        public string FO1_LongName {
            get {
                return ((string)(this["FO1_LongName"]));
            }
            set {
                this["FO1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mehoopany")]
        public string MH1_LongName {
            get {
                return ((string)(this["MH1_LongName"]));
            }
            set {
                this["MH1_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flat_Ridge_II")]
        public string FR2_LongName {
            get {
                return ((string)(this["FR2_LongName"]));
            }
            set {
                this["FR2_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fowler_III")]
        public string FO3_LongName {
            get {
                return ((string)(this["FO3_LongName"]));
            }
            set {
                this["FO3_LongName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trinity_I")]
        public string TH1_LongName {
            get {
                return ((string)(this["TH1_LongName"]));
            }
            set {
                this["TH1_LongName"] = value;
            }
        }
    }
}
