#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WindART_SMI")]
	public partial class WindART_SMIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFileLocation(FileLocation instance);
    partial void UpdateFileLocation(FileLocation instance);
    partial void DeleteFileLocation(FileLocation instance);
    partial void InsertFileFormat(FileFormat instance);
    partial void UpdateFileFormat(FileFormat instance);
    partial void DeleteFileFormat(FileFormat instance);
    partial void InsertFileFormatType(FileFormatType instance);
    partial void UpdateFileFormatType(FileFormatType instance);
    partial void DeleteFileFormatType(FileFormatType instance);
    partial void InsertLog(Log instance);
    partial void UpdateLog(Log instance);
    partial void DeleteLog(Log instance);
    partial void InsertProcessFile(ProcessFile instance);
    partial void UpdateProcessFile(ProcessFile instance);
    partial void DeleteProcessFile(ProcessFile instance);
    #endregion
		
		public WindART_SMIDataContext() : 
				base(global::Helper.Properties.Settings.Default.WindART_SMIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WindART_SMIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WindART_SMIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WindART_SMIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WindART_SMIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FileLocation> FileLocations
		{
			get
			{
				return this.GetTable<FileLocation>();
			}
		}
		
		public System.Data.Linq.Table<FileFormat> FileFormats
		{
			get
			{
				return this.GetTable<FileFormat>();
			}
		}
		
		public System.Data.Linq.Table<FileFormatType> FileFormatTypes
		{
			get
			{
				return this.GetTable<FileFormatType>();
			}
		}
		
		public System.Data.Linq.Table<Log> Logs
		{
			get
			{
				return this.GetTable<Log>();
			}
		}
		
		public System.Data.Linq.Table<ProcessFile> ProcessFiles
		{
			get
			{
				return this.GetTable<ProcessFile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileLocation")]
	public partial class FileLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileLocationId;
		
		private string _Folder;
		
		private string _FileMask;
		
		private System.Nullable<bool> _Recurse;
		
		private System.Nullable<int> _FileFormatId;
		
		private EntityRef<FileFormat> _FileFormat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileLocationIdChanging(int value);
    partial void OnFileLocationIdChanged();
    partial void OnFolderChanging(string value);
    partial void OnFolderChanged();
    partial void OnFileMaskChanging(string value);
    partial void OnFileMaskChanged();
    partial void OnRecurseChanging(System.Nullable<bool> value);
    partial void OnRecurseChanged();
    partial void OnFileFormatIdChanging(System.Nullable<int> value);
    partial void OnFileFormatIdChanged();
    #endregion
		
		public FileLocation()
		{
			this._FileFormat = default(EntityRef<FileFormat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileLocationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FileLocationId
		{
			get
			{
				return this._FileLocationId;
			}
			set
			{
				if ((this._FileLocationId != value))
				{
					this.OnFileLocationIdChanging(value);
					this.SendPropertyChanging();
					this._FileLocationId = value;
					this.SendPropertyChanged("FileLocationId");
					this.OnFileLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folder", DbType="VarChar(1000)")]
		public string Folder
		{
			get
			{
				return this._Folder;
			}
			set
			{
				if ((this._Folder != value))
				{
					this.OnFolderChanging(value);
					this.SendPropertyChanging();
					this._Folder = value;
					this.SendPropertyChanged("Folder");
					this.OnFolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileMask", DbType="VarChar(100)")]
		public string FileMask
		{
			get
			{
				return this._FileMask;
			}
			set
			{
				if ((this._FileMask != value))
				{
					this.OnFileMaskChanging(value);
					this.SendPropertyChanging();
					this._FileMask = value;
					this.SendPropertyChanged("FileMask");
					this.OnFileMaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recurse", DbType="Bit")]
		public System.Nullable<bool> Recurse
		{
			get
			{
				return this._Recurse;
			}
			set
			{
				if ((this._Recurse != value))
				{
					this.OnRecurseChanging(value);
					this.SendPropertyChanging();
					this._Recurse = value;
					this.SendPropertyChanged("Recurse");
					this.OnRecurseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatId", DbType="Int")]
		public System.Nullable<int> FileFormatId
		{
			get
			{
				return this._FileFormatId;
			}
			set
			{
				if ((this._FileFormatId != value))
				{
					if (this._FileFormat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFileFormatIdChanging(value);
					this.SendPropertyChanging();
					this._FileFormatId = value;
					this.SendPropertyChanged("FileFormatId");
					this.OnFileFormatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FileFormat_FileLocation", Storage="_FileFormat", ThisKey="FileFormatId", OtherKey="FileFormatId", IsForeignKey=true)]
		public FileFormat FileFormat
		{
			get
			{
				return this._FileFormat.Entity;
			}
			set
			{
				FileFormat previousValue = this._FileFormat.Entity;
				if (((previousValue != value) 
							|| (this._FileFormat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FileFormat.Entity = null;
						previousValue.FileLocations.Remove(this);
					}
					this._FileFormat.Entity = value;
					if ((value != null))
					{
						value.FileLocations.Add(this);
						this._FileFormatId = value.FileFormatId;
					}
					else
					{
						this._FileFormatId = default(Nullable<int>);
					}
					this.SendPropertyChanged("FileFormat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileFormat")]
	public partial class FileFormat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileFormatId;
		
		private System.Nullable<int> _FileFormatTypeId;
		
		private System.Nullable<int> _HeaderRowNumber;
		
		private string _HeaderRowContents;
		
		private string _TagPrefix;
		
		private System.Nullable<int> _TimeZoneId;
		
		private EntitySet<FileLocation> _FileLocations;
		
		private EntityRef<FileFormatType> _FileFormatType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileFormatIdChanging(int value);
    partial void OnFileFormatIdChanged();
    partial void OnFileFormatTypeIdChanging(System.Nullable<int> value);
    partial void OnFileFormatTypeIdChanged();
    partial void OnHeaderRowNumberChanging(System.Nullable<int> value);
    partial void OnHeaderRowNumberChanged();
    partial void OnHeaderRowContentsChanging(string value);
    partial void OnHeaderRowContentsChanged();
    partial void OnTagPrefixChanging(string value);
    partial void OnTagPrefixChanged();
    partial void OnTimeZoneIdChanging(System.Nullable<int> value);
    partial void OnTimeZoneIdChanged();
    #endregion
		
		public FileFormat()
		{
			this._FileLocations = new EntitySet<FileLocation>(new Action<FileLocation>(this.attach_FileLocations), new Action<FileLocation>(this.detach_FileLocations));
			this._FileFormatType = default(EntityRef<FileFormatType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FileFormatId
		{
			get
			{
				return this._FileFormatId;
			}
			set
			{
				if ((this._FileFormatId != value))
				{
					this.OnFileFormatIdChanging(value);
					this.SendPropertyChanging();
					this._FileFormatId = value;
					this.SendPropertyChanged("FileFormatId");
					this.OnFileFormatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatTypeId", DbType="Int")]
		public System.Nullable<int> FileFormatTypeId
		{
			get
			{
				return this._FileFormatTypeId;
			}
			set
			{
				if ((this._FileFormatTypeId != value))
				{
					if (this._FileFormatType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFileFormatTypeIdChanging(value);
					this.SendPropertyChanging();
					this._FileFormatTypeId = value;
					this.SendPropertyChanged("FileFormatTypeId");
					this.OnFileFormatTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeaderRowNumber", DbType="Int")]
		public System.Nullable<int> HeaderRowNumber
		{
			get
			{
				return this._HeaderRowNumber;
			}
			set
			{
				if ((this._HeaderRowNumber != value))
				{
					this.OnHeaderRowNumberChanging(value);
					this.SendPropertyChanging();
					this._HeaderRowNumber = value;
					this.SendPropertyChanged("HeaderRowNumber");
					this.OnHeaderRowNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeaderRowContents", DbType="VarChar(1000)")]
		public string HeaderRowContents
		{
			get
			{
				return this._HeaderRowContents;
			}
			set
			{
				if ((this._HeaderRowContents != value))
				{
					this.OnHeaderRowContentsChanging(value);
					this.SendPropertyChanging();
					this._HeaderRowContents = value;
					this.SendPropertyChanged("HeaderRowContents");
					this.OnHeaderRowContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagPrefix", DbType="VarChar(255)")]
		public string TagPrefix
		{
			get
			{
				return this._TagPrefix;
			}
			set
			{
				if ((this._TagPrefix != value))
				{
					this.OnTagPrefixChanging(value);
					this.SendPropertyChanging();
					this._TagPrefix = value;
					this.SendPropertyChanged("TagPrefix");
					this.OnTagPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZoneId", DbType="Int")]
		public System.Nullable<int> TimeZoneId
		{
			get
			{
				return this._TimeZoneId;
			}
			set
			{
				if ((this._TimeZoneId != value))
				{
					this.OnTimeZoneIdChanging(value);
					this.SendPropertyChanging();
					this._TimeZoneId = value;
					this.SendPropertyChanged("TimeZoneId");
					this.OnTimeZoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FileFormat_FileLocation", Storage="_FileLocations", ThisKey="FileFormatId", OtherKey="FileFormatId")]
		public EntitySet<FileLocation> FileLocations
		{
			get
			{
				return this._FileLocations;
			}
			set
			{
				this._FileLocations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FileFormatType_FileFormat", Storage="_FileFormatType", ThisKey="FileFormatTypeId", OtherKey="FileFormatTypeId", IsForeignKey=true)]
		public FileFormatType FileFormatType
		{
			get
			{
				return this._FileFormatType.Entity;
			}
			set
			{
				FileFormatType previousValue = this._FileFormatType.Entity;
				if (((previousValue != value) 
							|| (this._FileFormatType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FileFormatType.Entity = null;
						previousValue.FileFormats.Remove(this);
					}
					this._FileFormatType.Entity = value;
					if ((value != null))
					{
						value.FileFormats.Add(this);
						this._FileFormatTypeId = value.FileFormatTypeId;
					}
					else
					{
						this._FileFormatTypeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("FileFormatType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FileLocations(FileLocation entity)
		{
			this.SendPropertyChanging();
			entity.FileFormat = this;
		}
		
		private void detach_FileLocations(FileLocation entity)
		{
			this.SendPropertyChanging();
			entity.FileFormat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileFormatType")]
	public partial class FileFormatType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileFormatTypeId;
		
		private string _Name;
		
		private System.Nullable<char> _Delimitor;
		
		private EntitySet<FileFormat> _FileFormats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileFormatTypeIdChanging(int value);
    partial void OnFileFormatTypeIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDelimitorChanging(System.Nullable<char> value);
    partial void OnDelimitorChanged();
    #endregion
		
		public FileFormatType()
		{
			this._FileFormats = new EntitySet<FileFormat>(new Action<FileFormat>(this.attach_FileFormats), new Action<FileFormat>(this.detach_FileFormats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FileFormatTypeId
		{
			get
			{
				return this._FileFormatTypeId;
			}
			set
			{
				if ((this._FileFormatTypeId != value))
				{
					this.OnFileFormatTypeIdChanging(value);
					this.SendPropertyChanging();
					this._FileFormatTypeId = value;
					this.SendPropertyChanged("FileFormatTypeId");
					this.OnFileFormatTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delimitor", DbType="Char(1)")]
		public System.Nullable<char> Delimitor
		{
			get
			{
				return this._Delimitor;
			}
			set
			{
				if ((this._Delimitor != value))
				{
					this.OnDelimitorChanging(value);
					this.SendPropertyChanging();
					this._Delimitor = value;
					this.SendPropertyChanged("Delimitor");
					this.OnDelimitorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FileFormatType_FileFormat", Storage="_FileFormats", ThisKey="FileFormatTypeId", OtherKey="FileFormatTypeId")]
		public EntitySet<FileFormat> FileFormats
		{
			get
			{
				return this._FileFormats;
			}
			set
			{
				this._FileFormats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FileFormats(FileFormat entity)
		{
			this.SendPropertyChanging();
			entity.FileFormatType = this;
		}
		
		private void detach_FileFormats(FileFormat entity)
		{
			this.SendPropertyChanging();
			entity.FileFormatType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Log]")]
	public partial class Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogId;
		
		private System.Nullable<System.DateTime> _Time;
		
		private System.Nullable<byte> _LogSeverityId;
		
		private string _Process;
		
		private string _Message;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIdChanging(int value);
    partial void OnLogIdChanged();
    partial void OnTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeChanged();
    partial void OnLogSeverityIdChanging(System.Nullable<byte> value);
    partial void OnLogSeverityIdChanged();
    partial void OnProcessChanging(string value);
    partial void OnProcessChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    #endregion
		
		public Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogId
		{
			get
			{
				return this._LogId;
			}
			set
			{
				if ((this._LogId != value))
				{
					this.OnLogIdChanging(value);
					this.SendPropertyChanging();
					this._LogId = value;
					this.SendPropertyChanged("LogId");
					this.OnLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogSeverityId", DbType="TinyInt")]
		public System.Nullable<byte> LogSeverityId
		{
			get
			{
				return this._LogSeverityId;
			}
			set
			{
				if ((this._LogSeverityId != value))
				{
					this.OnLogSeverityIdChanging(value);
					this.SendPropertyChanging();
					this._LogSeverityId = value;
					this.SendPropertyChanged("LogSeverityId");
					this.OnLogSeverityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Process", DbType="VarChar(50)")]
		public string Process
		{
			get
			{
				return this._Process;
			}
			set
			{
				if ((this._Process != value))
				{
					this.OnProcessChanging(value);
					this.SendPropertyChanging();
					this._Process = value;
					this.SendPropertyChanged("Process");
					this.OnProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(1000)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProcessFile")]
	public partial class ProcessFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProcessFileId;
		
		private System.Nullable<System.DateTime> _ProcessDate;
		
		private string _OriginalName;
		
		private string _Name;
		
		private System.Nullable<int> _FileStatus;
		
		private System.Nullable<int> _FileLocationId;
		
		private System.Nullable<int> _FileFormatId;
		
		private System.Nullable<int> _SiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProcessFileIdChanging(int value);
    partial void OnProcessFileIdChanged();
    partial void OnProcessDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProcessDateChanged();
    partial void OnOriginalNameChanging(string value);
    partial void OnOriginalNameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFileStatusChanging(System.Nullable<int> value);
    partial void OnFileStatusChanged();
    partial void OnFileLocationIdChanging(System.Nullable<int> value);
    partial void OnFileLocationIdChanged();
    partial void OnFileFormatIdChanging(System.Nullable<int> value);
    partial void OnFileFormatIdChanged();
    partial void OnSiteIdChanging(System.Nullable<int> value);
    partial void OnSiteIdChanged();
    #endregion
		
		public ProcessFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessFileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProcessFileId
		{
			get
			{
				return this._ProcessFileId;
			}
			set
			{
				if ((this._ProcessFileId != value))
				{
					this.OnProcessFileIdChanging(value);
					this.SendPropertyChanging();
					this._ProcessFileId = value;
					this.SendPropertyChanged("ProcessFileId");
					this.OnProcessFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProcessDate
		{
			get
			{
				return this._ProcessDate;
			}
			set
			{
				if ((this._ProcessDate != value))
				{
					this.OnProcessDateChanging(value);
					this.SendPropertyChanging();
					this._ProcessDate = value;
					this.SendPropertyChanged("ProcessDate");
					this.OnProcessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalName", DbType="VarChar(8000)")]
		public string OriginalName
		{
			get
			{
				return this._OriginalName;
			}
			set
			{
				if ((this._OriginalName != value))
				{
					this.OnOriginalNameChanging(value);
					this.SendPropertyChanging();
					this._OriginalName = value;
					this.SendPropertyChanged("OriginalName");
					this.OnOriginalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(8000)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileStatus", DbType="Int")]
		public System.Nullable<int> FileStatus
		{
			get
			{
				return this._FileStatus;
			}
			set
			{
				if ((this._FileStatus != value))
				{
					this.OnFileStatusChanging(value);
					this.SendPropertyChanging();
					this._FileStatus = value;
					this.SendPropertyChanged("FileStatus");
					this.OnFileStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileLocationId", DbType="Int")]
		public System.Nullable<int> FileLocationId
		{
			get
			{
				return this._FileLocationId;
			}
			set
			{
				if ((this._FileLocationId != value))
				{
					this.OnFileLocationIdChanging(value);
					this.SendPropertyChanging();
					this._FileLocationId = value;
					this.SendPropertyChanged("FileLocationId");
					this.OnFileLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatId", DbType="Int")]
		public System.Nullable<int> FileFormatId
		{
			get
			{
				return this._FileFormatId;
			}
			set
			{
				if ((this._FileFormatId != value))
				{
					this.OnFileFormatIdChanging(value);
					this.SendPropertyChanging();
					this._FileFormatId = value;
					this.SendPropertyChanged("FileFormatId");
					this.OnFileFormatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="Int")]
		public System.Nullable<int> SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
